-- 1. What is the total revenue generated by male vs. female customers?
select gender, SUM()










-- What are the top 5 products with average highest review rating?
select "Item Purchased",ROUND(AVG("Review Rating")::numeric,2) as review_rating
from customer
group by "Item Purchased"
order by review_rating DESC
limit 5;
-- Which 5 products have the highest percentage of purchases with discount applied?

SELECT 
    "Item Purchased",
    COUNT(*) FILTER (WHERE "Discount Applied" = 'Yes') AS discounted_count
FROM customer
GROUP BY "Item Purchased"
limit 5;
--Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.



