-- 1.	What is the total revenue generated by male vs. female customers? 
select "Gender", SUM("Purchase Amount (USD)") as revenue
from customer
group by "Gender"

-- 2. Which customers used a discount but still spent more than the average purchase amount? 
select "Customer ID", "Purchase Amount (USD)"
from customer
where "Discount Applied" ='Yes' and "Purchase Amount (USD)"> (select AVG("Purchase Amount (USD)") FROM customer)


-- 3. Which are the top 5 products with the highest average review rating? 
select "Item Purchased",ROUND(AVG("Review Rating")::numeric,2)
from customer
group by "Item Purchased"
order by AVG("Review Rating") DESC
limit 5;

-- 4.Compare the average Purchase Amounts between Standard and Express Shipping. 
select "Shipping Type", ROUND(AVG("Purchase Amount (USD)")::numeric,2)
from customer
where "Shipping Type" in ('Standard' , 'Express')
group by "Shipping Type";

-- 5.Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

select "Subscription Status", Count("Customer ID") as total_customers,
ROUND(AVG("Purchase Amount (USD)")::numeric,2) as average_spend,
SUM("Purchase Amount (USD)") as total_revenue
from customer
group by "Subscription Status"
order by average_spend,total_revenue desc

-- 6.Which 5 products have the highest percentage of purchases with discounts applied? 
select "Item Purchased", 
ROUND(100*(SUM(CASE WHEN "Discount Applied" ='Yes' THEN 1 ELSE 0 END))/count(*),2)as discount_rate
from customer
group by "Item Purchased"
order by discount_rate desc
LIMIT 5;

-- 7.	Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 
with customer_type as (
select "Customer ID","Previous Purchases",
CASE
WHEN "Previous Purchases" = 0 THEN 'New'
WHEN "Previous Purchases" BETWEEN 2 AND 10 THEN 'Returning'
ELSE 'Loyal'
END as customer_segment
from customer
)
select customer_segment, count(customer_segment) as "Number of customer"
from customer_type
group by customer_segment


-- 8.	What are the top 3 most purchased products within each category? 
select "Category","Item Purchased",purchase_count
from (select 
	"Category",
	"Item Purchased",
	Count(*) as purchase_count,
	RANK() OVER(
	PARTITION BY "Category"
	ORDER BY Count(*) Desc)
	AS rank
	from customer
	group by "Category","Item Purchased")
	ranked
	where rank <=3
	

-- 9.	Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe? 
SELECT 
    customer_type,
    "Subscription Status",
    COUNT(*) AS count,
    ROUND(
        COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (PARTITION BY customer_type),
        2
    ) AS percentage
FROM (
    SELECT 
        CASE 
            WHEN "Previous Purchases" > 5 THEN 'Repeat Buyer'
            ELSE 'Non-Repeat Buyer'
        END AS customer_type,
        "Subscription Status"
    FROM customer
) sub
GROUP BY customer_type, "Subscription Status";



-- 2nd Answer
select "Subscription Status", Count("Customer ID") as repeat_buyers
from customer
where "Previous Purchases" > 5
group by "Subscription Status"

-- 10. What is the revenue contribution of each age group?

select "age_group",
SUM("Purchase Amount (USD)") As  Revenue
from customer
group by "age_group"
order by Revenue DESC;


